### PR TITLE
Pass environment variables to functional tests

### PR DESCRIPTION
**Pull request by pcmxgti**

### CODE REVIEW

**Comment by kittysyddy** [comment]
is the secret TOKENDITO_PYTEST_OPTIONS for uploading to pytest? is it a good practice to document what the secrets are for so that broken or unexpected behaviors in forks would make sense?

**Comment by pcmxgti** [comment]
I'll add more information to the testing README. Secrets aren't available in forks, so this is a no-op to everyone except maintainers.

**Comment by pcmxgti** [comment]
@sevignyj @JadyDJ I'd appreciate your thoughts on the direction of this PR before I finalize it.

**Comment by JadyDJ** [comment]
It makes sense to me to use pyotp for testing auth as we also use same lib in Jenkins validation.

**Comment by pcmxgti** [comment]
@JadyDJ @sevignyj - ready for review

**Review by JadyDJ — APPROVED** [review]

**Pull request merged**
