### PR TITLE
Add support for Duo MFA.

### PR DESCRIPTION
**Pull request by hb3b**

### CODE REVIEW

**Comment by hb3b** [comment]
@sydneysweeneydj @pcmxgti Can you please review when you have a chance?

**Comment by sydneysweeneydj** [comment]
Hi Ben @hb3b , thanks for making a PR with us!! We are willing to add support for Duo but I am spiking if there is a way for us to avoid the web browser technique in favor of the Duo API. I created my own instances of Duo and Okta to test this MFA option. I will see if we can conform to the same method for Duo factors as with Okta factors, including having the push option poll Duo until the user confirms.

**Comment by hb3b** [comment]
Hi @sydneysweeneydj! The flow you described is certainly ideal but it would require us to implement browserless auth for each mode supported by Duo. As you can see here: https://github.com/segmentio/aws-okta/blob/master/lib/duo.go It's not a trivial implementation. Our employees use a mix of Push, U2F, and TOTP all of which would need to be supported.

In any event, I will do some experimentation to see what can be done to implement browserless push support. Thank you for taking a look!

**Comment by sydneysweeneydj** [comment]
hi @hb3b , I have gotten something roughly working that looks like this:

`🖖 python -m tokendito
Select your preferred MFA method and press Enter
[0] OKTA    token:software:totp
[1] DUO     web
-> 1
Select your preferred MFA method and press Enter
[0] Duo Push      phone1 - iOS (XXX-XXX-4253)
[1] Phone Call    phone1 - iOS (XXX-XXX-4253)
[2] Passcode      phone1 - iOS (XXX-XXX-4253)`

I used the code you shared and burp to help me figure out all of the endpoints. The general flow is similar to the Go code, following the /frame/web/v1/auth paths in Duo, and using beautifulsoup to parse Duo responses to list out each mfa option for each device that the user has registered. I will cut a PR when the code is a little more bearable, and would love your help to test it out in your environment and with additional types of MFA!

**Comment by kittysyddy** [comment]
hi @hb3b , i wanted to let you know that we merged this feature into master and cut a release today!!!!!! please check it out!!!! :)

**Pull request closed without merging**
